{
 "title": "ProjetoObservability",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hora da inicialização da API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tempo de atividade da API (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"apicrudv1\"} == 1) / count(up{job=\"apicrudv1\"})*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "uso de CPU da API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{job=\"apicrudv1\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Soma de Quantidade de Requisições HTTP na API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"apicrudv1\"})"
    }
   ]
  },
  {
   "title": "tempo total de CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"web:8080\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_cpu_seconds_total{instance=\"localhost:9090\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_cpu_seconds_total{instance=\"cadvisor:8080\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Volumetria API",
   "type": "stat",
   "description": "Total de Requests nos últimos 5 minutos",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"web:8080\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Soma de recursos Abertos da API nos últimos 5 minutos",
   "type": "timeseries",
   "description": "Um “handle” é uma referência a um recurso aberto, como um arquivo aberto, uma conexão de banco de dados ou uma solicitação. Um handle é considerado “ativo” se ainda estiver fazendo algo ou se ainda puder fazer algo.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "increase(nodejs_active_handles[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requisições por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (method, path, apicrudv1)(rate(http_request_duration_seconds_count[2m]))",
     "legendFormat": "{{method}} {{path}} {{apicrudv1}}"
    }
   ]
  },
  {
   "title": "HTTP Status por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "sum by (status_code, crudapiv1)(rate(http_request_duration_seconds_count[2m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Tempo de Resposta Médio para retorno do Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (status_code, crudapiv1) /\r\nsum(rate(http_request_duration_seconds_count[5m])) by (status_code, crudapiv1)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Informações por Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Quantidade de Containers Ativos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Utilização de CPU %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "(rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Utilização de Memória",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus\",image!=\"\"} - container_memory_cache{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus| web\",image!=\"\"})",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Tráfego de Entrada por Container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tráfego de Saída por Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}