version: '3'
services:

  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - "9090:9090"
    networks:
      - backend
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    deploy:
      mode: global
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  alertmanager:
    image: prom/alertmanager:v0.25.0
    networks:
      - backend
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/data
    command: --config.file=/etc/alertmanager/alertmanager.yml

  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    networks:
        - backend

  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    networks:
      - backend
      - frontend

  wordpress_exporter:
    depends_on:
      - mariadb
    image: erwin82/wordpress_exporter:latest
    ports:
      - "8888:8888"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=bitnami_wordpress
    networks:
        - backend

  jaeger:
    container_name: jeager_tracing
    image: jaegertracing/all-in-one
    networks:
      - backend
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  prometheus-data:
  grafana-data:
  alertmanager-data:

networks:
  frontend:
  backend: