version: '3'
services:

  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - "9090:9090"
    networks:
      - backend
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    deploy:
      mode: global
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  alertmanager:
    image: prom/alertmanager:v0.25.0
    networks:
      - backend
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/data
    command: --config.file=/etc/alertmanager/alertmanager.yml

  mysqldb:
    image: mysql:5.7
    restart: always
    volumes:
      - mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
        - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_DB: my_database

  wordpress:
    depends_on:
      - mysqldb
    image: wordpress:latest
    volumes:
      - wordpress-data:/var/www/html
    ports:
        - "80:80"
    networks:
        - backend
    environment:
      WORDPRESS_DB_HOST: mysqldb:3306
      WORDPRESS_DB_USER: my_user
      WORDPRESS_DB_PASSWORD: my_password
      WORDPRESS_DB_NAME: my_database

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
  mysqldb-data:
  wordpress-data:

networks:
  frontend:
  backend: