{
 "title": "Projeto Observability",
 "description": "Rafael Ferreira, Vanessa, Ana Beatriz, Laysa",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hora de Inicialização da API",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1000*(process_start_time_seconds{job=\"apicrudv1\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Requisições por minuto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (method, path, apicrudv1)(rate(http_request_duration_seconds_count[2m]))",
       "legendFormat": "{{method}} {{path}} {{apicrudv1}}"
      }
     ]
    },
    {
     "title": "Tempo Disponível da API no último dia",
     "type": "timeseries",
     "description": "O eixo Y a % de tempo de atividade da API. Por exemplo, se em um determinado ponto no eixo X (digamos, 00:40), o ponto correspondente no eixo Y é 70, isso significa que a API esteve ativa e funcionando corretamente 70% do tempo até aquele momento.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "100 * avg_over_time(up{job='apicrudv1'}[1d])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "HTTP Status por minuto",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (status_code, crudapiv1)(rate(http_request_duration_seconds_count[2m]))",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Taxa de erro dos últimos 5 minutos",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(http_requests_total{status=\"500\"}[5m]))"
      },
      {
       "expr": "sum(increase(http_requests_total{status=\"400\"}[5m]))"
      },
      {
       "expr": "sum(increase(http_requests_total{status=\"404\"}[5m]))"
      }
     ]
    },
    {
     "title": "Tempo de Resposta Médio para retorno do Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (status_code, crudapiv1) /\r\nsum(rate(http_request_duration_seconds_count[5m])) by (status_code, crudapiv1)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Soma de recursos Abertos da API nos últimos 5 minutos",
     "type": "timeseries",
     "description": "Um “handle” é uma referência a um recurso aberto, como um arquivo aberto, uma conexão de banco de dados ou uma solicitação. Um handle é considerado “ativo” se ainda estiver fazendo algo ou se ainda puder fazer algo.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "increase(nodejs_active_handles[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Volumetria API",
     "type": "stat",
     "description": "Total de Requests nos últimos 5 minutos",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"web:8080\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Soma de Quantidade de Requisições HTTP na API",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_total{job=\"apicrudv1\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Informações por Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quantidade de Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 14, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(container_last_seen{name=~\".+\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Utilização de CPU %",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 7, "x": 4, "y": 5 },
     "targets": [
      {
       "expr": "(rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus\",image!=\"\"}[5m]) * 100)\n",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "Utilização de Memória",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 7, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus\",image!=\"\"} - container_memory_cache{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|web|prometheus| web\",image!=\"\"})\n",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "Tráfego de Entrada por Container",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 7, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Tráfego de Saída por Container",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 7, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}