AWSTemplateFormatVersion: 2010-09-09
Description: Provisionamento da infraestrutura para o projeto de Observabilidade

################################### PARAMETERS ###################################

Parameters:

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: VPC ID

    Subnet:
        Type: AWS::EC2::Subnet::Id
        Description: Subnet ID

    KeyName:
        Type: AWS::EC2::KeyPair::KeyName
        Description: Key Pair Name

    InstanceType:
        Type: String
        Description: EC2 instance type
        Default: t2.micro
        AllowedValues:
          - t2.micro
          - t2.medium

################################### METADATA ###################################

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "REDE"
        Parameters:
          - VPC
          - Subnet
      - Label:
          default: "EC2"
        Parameters:
          - InstanceType
          - KeyName
    ParameterLabels:
      VPC:
        default: "VPC ID"
      Subnet:
        default: "Subnet ID"
      InstanceType:
        default: "EC2 instance type"
      KeyName:
        default: "Key Pair Name"

################################### MAPPINGS ###################################

Mappings:

  AWSRegionToAMI:
    us-east-1:
      AMI: ami-03eb6185d756497f8

################################### RESOURCES ###################################

Resources:

  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  EC2SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      Roles:
        - !Ref EC2Role
      SecurityGroupIds:
        - !Ref EC2SecurityGroupSSH
      ImageId: !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo amazon-linux-extras install docker -y
          sudo service docker start
          sudo systemctl enable docker
          sudo usermod -a -G docker ssm-user
          sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          cd
          git clone https://github.com/rafae1f/Projeto-Observability.git