global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  - 'alert.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
          - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 5s
    static_configs:
         - targets: ['YOUR_NETDATA_IP:19999']

  - job_name: 'mariadb'
    scrape_interval: 5s
    static_configs:
          - targets: ['mariadb:3306']

  - job_name: "wordpress"
    scrape_interval: 5s
    static_configs:
          - targets: [ 'wordpress:80' ]

  - job_name: "wordpress exporter"
    scrape_interval: 5s
    static_configs:
          - targets: [ 'wordpress_exporter:8888' ]

  - job_name: "wordpress metrics"
    static_configs:
      - targets: ["domain.tld"]
    scrape_interval: "5m"
    metrics_path: "/wp-json/metrics"
    params:
      prometheus: ['fg98dfgkj']
      users: ['yes']
      posts: ['yes']
      pages: ['yes']
      autoload: ['yes']
      transient: ['yes']
      user_sessions: ['yes']
      posts_without_content: ['yes']
      posts_without_title: ['yes']
      db_size: ['yes']
      pending_updates: ['yes']
    scheme: "https"